import './globals.css'

// import ClerkProvider from '@clerk/next'

import { Bungee } from 'next/font/google'
import { Aleo } from 'next/font/google'

const bungee = Bungee({ subsets: ['latin'], weight: '400' })
const aleo = Aleo({ subsets: ['latin'], weight: '700' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bungee.className, aleo.className}>
        {children}
      </body>
    </html>
  )
}